print("Welcome")
total_bill =float((input("what was the total beill?")))
tip =int(input("How much tip wold you like to give? 10, 12 or 15?"))
num_of_people = int(input("How many people to splite the bill?"))
total = round(((total_bill + ((tip / 100) * total_bill))/num_of_people), 2)
print(f"each person should pay: {total}")